---
# tasks file for ansible_vim
- name: Install python3
  dnf:
    name: python3
    state: latest
  become: yes

# tasks file for ansible_vim
- name: Install pip3
  dnf:
    name: python3-pip
    state: latest
  become: yes

# tasks file for ansible_vim
- name: Install virtualenv
  dnf:
    name: python3-virtualenv
    state: latest
  become: yes
